const doctors = [
  {
    id: 1,
    name: "Iqbal Ali Jamsed",
    department: "Cardiology",
    visitingTime: "4pm - 8pm",
    visitingDay: "Mon-Fri",
    fee: "50USD",
    img: "https://i.ibb.co/GWQgc9S/doctor1.jpg",
  },
  {
    id: 2,
    name: "Kamal Tosif",
    department: "Orthopedic",
    visitingTime: "5pm - 9pm",
    visitingDay: "Sat-Sun",
    fee: "40USD",
    img: "https://i.ibb.co/nLj0pDp/doctor2.jpg",
  },
  {
    id: 3,
    name: "Steve Smith",
    department: "Medicine",
    visitingTime: "7pm - 10pm",
    visitingDay: "Mon-Fri",
    fee: "60USD",
    img: "https://i.ibb.co/M6GmT2p/doctor3.jpg",
  },
  {
    id: 4,
    name: "Ryhan Mollah",
    department: "Neurology",
    visitingTime: "3pm - 8pm",
    visitingDay: "Sat-Sun",
    fee: "70USD",
    img: "https://i.ibb.co/KxKcr32/doctor4.jpg",
  },
  {
    id: 5,
    name: "Jafor Khan",
    department: "Radiology",
    visitingTime: "6pm - 8pm",
    visitingDay: "Mon-Fri",
    fee: "50USD",
    img: "https://i.ibb.co/9N9rHBM/doctor5.jpg",
  },
  {
    id: 6,
    name: "Jogodis Chandra Sen",
    department: "Skin Specialist  ",
    visitingTime: "6pm - 8pm",
    visitingDay: "Monday-Friday",
    fee: "50USD",
    img: "https://i.ibb.co/kDVWRG9/doctor6.jpg",
  },
  {
    id: 7,
    name: "Refat Ali Khan",
    department: "Nutritionists",
    visitingTime: "4pm - 7pm",
    visitingDay: "Mon-Fri",
    fee: "40USD",
    img: "https://i.ibb.co/B4VPqQW/doctor7.jpg",
  },
  {
    id: 8,
    name: "Ryhan Tosif",
    department: "Urologists",
    visitingTime: "4pm - 8pm",
    visitingDay: "Mon-Fri",
    fee: "60USD",
    img: "https://i.ibb.co/dPCYWgN/doctor8.jpg",
  },
];
