const servicesInfo = [
    {
        id:101,
        name:'Ambulance',
        number: 15, 
        des: "We have qualityful 15 ambulance for our customers. The ambulances have different facilities for the patients like, Oxyzen Chilender and having a skilled staff altime in the ambulnace for emergency support for the patient.", 
        price: "5000-12000",
        details: "Service Fee within Dhaka is 7000 and Service Fee Outside Dhaka 12000",
        img: "https://i.ibb.co/nkwPykX/ambulance.png",
    },
    {
        id:102,
        name:'Doctors',
        number: 20, 
        des: "We have qualityful 20 parmanents Doctors for our Patients. 10 Doctors will remains 24 hours to ensure best serve for our patients. They are highly qualified Professor in different Department and experiences more than 10 years.", 
        price: "1000-2000",
        details: "Visit free: 1000 for Register Members and 2000 for non-Register Members",
        img: "https://i.ibb.co/f418pwP/doctors.png",
    },
    {
        id:103,
        name:'Diagonistic',
        number: 3, 
        des: "We three Diagonistic Lab having 20 qualitiful staff to genrate reports for our patient. They collects the sample and serving test reports for the patients. They are commited and trustowrthy for their jobs.Most of them are serving patient more than 5 years in our hospital", 
        price: "100-2500",
        details: "Blood test 100-2000, MRI test 5000, SBI test 300",
        img: "https://i.ibb.co/HGqKftp/Diagonistic.png",
    },
    {
        id:104,
        name:'Nurses',
        number: 100, 
        des: "We have qualityful 50 Nurses for our Patients. Thirty Nurses will commited to serve all the time for the Patient. They are very much Empathitic and Respectful to our patients.  ", 
        price: "1500-2000",
        details: "1500 to 2000 per day when they go individual patient residence",
        img: "https://i.ibb.co/vhgTXmb/Nurses.png",
    },
    {
        id:105,
        name:'Cabin',
        number: 50, 
        des: "We have standard,premium and general 50 Cabin for our patient. It's also provide emergency madical equipment attached with the cabin and a nurse will be parmanent for 2/3 cabin based on requirement of the patient.", 
        price: "3500-9000",
        details: "General Cabin: 3500/day Standard Cabing: 6000/day and Premium Cabin: 9000/day",
        img: "https://i.ibb.co/3S6ffn1/Cabin.png",
    },
    {
        id:106,
        name:'Operation Theater',
        number: 5, 
        des: "We have 5 OT for surgical procedure for the patient. We have standard and qualitiful OT where experts doctors can immediate do any surgery when needed for patients. We have done more than 5000 successful operations from our hospital.", 
        price: "5000-500000",
        details: "Cost may very From basis on operation Difficulties level or patients situations.",
        img: "https://i.ibb.co/KrT38T2/OT.png",
    }
]